// apps/web/src/app/components/Socials.tsx
export default function Socials() {
  const socials = [
    {
      name: 'Support Me',
      icon: '👍',
      url: 'https://buymeacoffee.com/toxey',
    },
  ];

  const openTab = (url: string) => {
    window.open(url, '_blank', 'noopener,noreferrer');
  };

  return (
    <div className="flex gap-3 my-4 justify-center">
      {socials.map((social, index) => (
        <button
          key={index}
          onClick={() => openTab(social.url)}
          className="flex items-center gap-2 px-4 py-2 bg-blue-600 text-white rounded-full hover:bg-blue-700 transition-colors shadow-md"
        >
          <span>{social.icon}</span>
          <span>{social.name}</span>
        </button>
      ))}
    </div>
  );
}

// src/app/features/socials/socials.component.ts
import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';
import { ButtonModule } from 'primeng/button';
@Component({
  selector: 'app-socials',
  standalone: true,
  imports: [ButtonModule, CommonModule],
  templateUrl: './socials.component.html',
  styleUrl: './socials.component.scss',
})
export class SocialsComponent {
  socials = [
    {
      name: 'Support Me',
      icon: 'pi pi-thumbs-up-fill',
      url: 'https://buymeacoffee.com/toxey',
    },
  ];
  openTab(url: string): void {
    window.open(url, '_blank');
  }
}

<div class="flex gap-3 my-2 justify-content-center">
  @for (social of socials; track $index) {
  <button
    pButton
    [raised]="true"
    [rounded]="true"
    icon="{{ social.icon }}"
    size="small"
    label="{{ social.name }}"
    (click)="openTab(social.url)"
  ></button>
  }
</div>
